# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-EbAMtTbpnv4P11oMNeKOceRkxbPcVv
"""

"""
PROJECT: Nelson-Siegel Yield Curve Calibration and Macro Tracking
ROLE: Senior Quantitative Developer Implementation
"""

# =============================================================================
# 1. PROJECT OVERVIEW & DOCUMENTATION
# =============================================================================
"""
1. Project Overview: A quantitative engine to parameterize the U.S. Treasury Term Structure
   using the Nelson-Siegel (NS) model, decomposing the curve into Level, Slope, and Curvature.

2. Real-World Use Case: Fixed income relative value (RV) trading and macro regime identification.

3. System Architecture:
   [Data Source: FRED] -> [Preprocessing: Pandas] -> [Optimization: Scipy] -> [Viz: Plotly]

4. Required APIs: St. Louis FED (FRED).

5. Required Libraries: pandas, numpy, scipy, plotly, pandas_datareader.

6. Resume Description: Developed a Nelson-Siegel term structure model to calibrate US Treasury
   yield curves. Implemented non-linear least squares optimization to extract latent macro
   factors (Level, Slope, Curvature) for regime shift detection.
"""

import numpy as np
import pandas as pd
import pandas_datareader.data as web
from scipy.optimize import minimize
import plotly.graph_objects as go
from datetime import datetime, timedelta
import warnings

warnings.filterwarnings('ignore')

# =============================================================================
# 2. DATA COLLECTION PIPELINE
# =============================================================================

def fetch_treasury_data(years=10):
    """Fetches constant maturity Treasury rates from FRED."""
    symbols = {
        'DGS1MO': 1/12, 'DGS3MO': 3/12, 'DGS6MO': 6/12,
        'DGS1': 1, 'DGS2': 2, 'DGS3': 3, 'DGS5': 5,
        'DGS7': 7, 'DGS10': 10, 'DGS20': 20, 'DGS30': 30
    }
    start = datetime.now() - timedelta(days=years*365)
    try:
        df = web.DataReader(list(symbols.keys()), 'fred', start)
        df = df.dropna()
        maturities = np.array(list(symbols.values()))
        return df, maturities
    except Exception as e:
        print(f"Error fetching data: {e}")
        return None, None

# =============================================================================
# 3. CORE NELSON-SIEGEL ALGORITHM
# =============================================================================

def nelson_siegel(tau, beta0, beta1, beta2, lamba):
    """
    Calculates the yield for maturity tau based on Nelson-Siegel parameters.
    Beta0: Level, Beta1: Slope, Beta2: Curvature, Lamba: Decay factor
    """
    # Handle tau=0 to avoid division by zero
    tau = np.maximum(tau, 1e-6)

    component1 = (1 - np.exp(-lamba * tau)) / (lamba * tau)
    component2 = component1 - np.exp(-lamba * tau)

    yield_val = beta0 + (beta1 * component1) + (beta2 * component2)
    return yield_val

def objective_function(params, maturities, yields):
    """Sum of squared residuals for calibration."""
    beta0, beta1, beta2, lamba = params
    predictions = nelson_siegel(maturities, beta0, beta1, beta2, lamba)
    return np.sum((yields - predictions)**2)

def calibrate_yield_curve(maturities, yields):
    """Calibrates NS parameters for a single day."""
    # Initial guess: [Level (avg yield), Slope (long-short), Curvature, Lambda]
    initial_guess = [yields.iloc[-1], yields.iloc[-1] - yields.iloc[0], 0, 1.0]

    res = minimize(objective_function, initial_guess, args=(maturities, yields),
                   method='Nelder-Mead', tol=1e-6)
    return res.x if res.success else [np.nan]*4

# =============================================================================
# 4. EXECUTION ENGINE
# =============================================================================

print("--- Starting Yield Curve Engine ---")
df_rates, maturities = fetch_treasury_data(years=5)

if df_rates is not None:
    print(f"Data loaded: {len(df_rates)} observations.")

    # Calibrate parameters over time (sampling monthly for performance in viz)
    monthly_df = df_rates.resample('ME').last()
    results = []

    for date, row in monthly_df.iterrows():
        params = calibrate_yield_curve(maturities, row)
        results.append({'Date': date, 'Beta0': params[0], 'Beta1': params[1],
                        'Beta2': params[2], 'Lambda': params[3]})

    df_params = pd.DataFrame(results).set_index('Date')

    # =============================================================================
    # 5. VISUALIZATION (3D SURFACE)
    # =============================================================================

    # Create meshgrid for surface
    plot_maturities = np.linspace(0.1, 30, 50)
    z_data = []

    for _, row in df_params.iterrows():
        y_row = nelson_siegel(plot_maturities, row['Beta0'], row['Beta1'],
                              row['Beta2'], row['Lambda'])
        z_data.append(y_row)

    z_data = np.array(z_data)

    fig = go.Figure(data=[go.Surface(z=z_data,
                                   x=plot_maturities,
                                   y=df_params.index,
                                   colorscale='Viridis')])

    fig.update_layout(title='Nelson-Siegel Yield Curve Term Structure Evolution',
                      scene=dict(xaxis_title='Maturity (Years)',
                                 yaxis_title='Time',
                                 zaxis_title='Yield (%)'),
                      margin=dict(l=0, r=0, b=0, t=40),
                      width=1000, height=700)
    fig.show()

    print("--- Calibration Complete ---")
    print(df_params.tail())
else:
    print("Execution failed due to data issues.")

import numpy as np
import pandas as pd
import pandas_datareader.data as web
from scipy.optimize import minimize
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta
import warnings

warnings.filterwarnings('ignore')

class FREDDataEngine:
    """Handles institutional-grade data retrieval and cleaning from FRED."""
    TICKERS = {
        'DGS1MO': 1/12, 'DGS3MO': 3/12, 'DGS6MO': 6/12,
        'DGS1': 1, 'DGS2': 2, 'DGS3': 3, 'DGS5': 5,
        'DGS7': 7, 'DGS10': 10, 'DGS20': 20, 'DGS30': 30
    }

    def __init__(self, years_back=5):
        self.start_date = datetime.now() - timedelta(days=years_back*365)
        self.maturities = np.array(list(self.TICKERS.values()))

    def fetch_weekly_data(self):
        try:
            df = web.DataReader(list(self.TICKERS.keys()), 'fred', self.start_date)
            df = df.ffill().dropna()
            df['Spread_10Y2Y'] = df['DGS10'] - df['DGS2']
            weekly_df = df.resample('W').last()
            return weekly_df
        except Exception as e:
            raise ConnectionError(f"FRED API Error: {e}")

class NSSCurveModel:
    """Advanced Nelson-Siegel-Svensson Engine with Regularization."""
    def __init__(self, l2_lambda=0.005):
        self.l2_lambda = l2_lambda

    @staticmethod
    def nss_formula(tau, b0, b1, b2, b3, l1, l2):
        tau = np.maximum(tau, 1e-6)
        term1 = (1 - np.exp(-l1 * tau)) / (l1 * tau)
        term2 = term1 - np.exp(-l1 * tau)
        term3 = ((1 - np.exp(-l2 * tau)) / (l2 * tau)) - np.exp(-l2 * tau)
        return b0 + b1*term1 + b2*term2 + b3*term3

    def calibrate(self, yields, maturities, last_params=None):
        def objective(params):
            b0, b1, b2, b3, l1, l2 = params
            preds = self.nss_formula(maturities, b0, b1, b2, b3, l1, l2)
            mse = np.mean((yields - preds)**2)
            penalty = self.l2_lambda * (b2**2 + b3**2)
            return mse + penalty

        bounds = [(0, 15), (-15, 15), (-20, 20), (-20, 20), (0.2, 5.0), (0.2, 5.0)]
        init_guess = last_params if last_params is not None else [yields.iloc[-1], yields.iloc[-1]-yields.iloc[0], 0, 0, 1.0, 2.0]
        res = minimize(objective, init_guess, method='L-BFGS-B', bounds=bounds, tol=1e-7)
        return res.x if res.success else np.full(6, np.nan)

class QuantDashboard:
    """Advanced Macro Portfolio Dashboard with Corrected Regime Classification."""
    def __init__(self, df_params, df_rates, maturities):
        self.df_params = df_params
        self.df_rates = df_rates
        self.maturities = maturities

    def classify_regime(self, slope_param):
        # In NS: Spread (L-S) = -Beta1.
        # Normal (Positive Spread) -> Negative Beta1
        # Inverted (Negative Spread) -> Positive Beta1
        if slope_param < -0.5: return ("Expansionary (Steep)", "#00FF00")
        elif slope_param > 0.1: return ("Recession Warning (Inverted)", "#FF4136")
        else: return ("Transition (Flat)", "#AAAAAA")

    def render(self):
        curr_beta1 = self.df_params['Beta1'].iloc[-1]
        regime_name, regime_color = self.classify_regime(curr_beta1)

        fig = make_subplots(
            rows=2, cols=2,
            specs=[[{"type": "xy"}, {"type": "xy"}],
                   [{"type": "surface", "colspan": 2}, None]],
            subplot_titles=("Curve Analysis: Today vs 1M Ago", f"Regime Tracking (-Beta1 vs 10Y2Y)", "3D Term Structure Evolution")
        )

        # 1. 2D Curve (Top Left) - Restore 1M comparison
        today = self.df_rates.drop(columns=['Spread_10Y2Y']).iloc[-1]
        one_month_ago = self.df_rates.drop(columns=['Spread_10Y2Y']).iloc[-5] if len(self.df_rates) > 5 else self.df_rates.iloc[0]
        fig.add_trace(go.Scatter(x=self.maturities, y=today, name='Live Curve', line=dict(width=4, color='cyan')), row=1, col=1)
        fig.add_trace(go.Scatter(x=self.maturities, y=one_month_ago, name='1M Ago', line=dict(dash='dot', color='gray')), row=1, col=1)

        # 2. Factor Evolution & Regime Shading (Top Right) - Plot -Beta1
        implied_slope = -self.df_params['Beta1']
        for i in range(len(self.df_params)-1):
            if self.df_params['Beta1'].iloc[i] > 0.1: # Inverted
                fig.add_vrect(x0=self.df_params.index[i], x1=self.df_params.index[i+1],
                              fillcolor="red", opacity=0.2, layer="below", line_width=0, row=1, col=2)

        fig.add_trace(go.Scatter(x=self.df_params.index, y=implied_slope, name='-Beta1 (Model Slope)', line=dict(color='orange', width=3)), row=1, col=2)
        fig.add_trace(go.Scatter(x=self.df_rates.index, y=self.df_rates['Spread_10Y2Y'], name='10Y-2Y (Bench)', line=dict(color='white', dash='dot', width=1)), row=1, col=2)

        # 3. 3D Surface (Bottom)
        plot_mats = np.linspace(0.1, 30, 40)
        z_matrix = np.array([NSSCurveModel.nss_formula(plot_mats, *p) for p in self.df_params.values])
        fig.add_trace(go.Surface(z=z_matrix, x=plot_mats, y=self.df_params.index, colorscale='Viridis', showscale=False), row=2, col=1)

        fig.add_annotation(dict(xref="paper", yref="paper", x=0.5, y=1.1, text=f"CURRENT REGIME: <span style='color:{regime_color}'>{regime_name.upper()}</span>", showarrow=False, font=dict(size=18, color="white")))
        fig.update_layout(height=950, width=1200, template="plotly_dark", margin=dict(t=100))
        fig.show()

class DataExporter:
    """Utility to persist signals for downstream analysis."""
    @staticmethod
    def export_to_csv(df, filename="nss_macro_signals.csv"):
        df.to_csv(filename)
        print(f"Successfully exported {len(df)} records to {filename}")

# --- Pipeline Execution ---
engine = FREDDataEngine(years_back=5)
rates = engine.fetch_weekly_data()
model = NSSCurveModel()

param_results = []
prev_params = None

for date, row in rates.drop(columns=['Spread_10Y2Y']).iterrows():
    optimized_params = model.calibrate(row, engine.maturities, last_params=prev_params)
    prev_params = optimized_params if not np.isnan(optimized_params).any() else prev_params
    param_results.append([*optimized_params])

df_params = pd.DataFrame(param_results, index=rates.index, columns=['Beta0','Beta1','Beta2','Beta3','Lambda1','Lambda2']).dropna()
dashboard = QuantDashboard(df_params, rates, engine.maturities)
dashboard.render()

DataExporter.export_to_csv(df_params)