import numpy as np
import pandas as pd
import pytest
from scipy.linalg import solve_discrete_lyapunov

from nss_engine.models import ns_loadings
from nss_engine.statespace import (
    DNSParameters,
    _Transform,
    evaluate_dns_forecasts,
    fit_dns,
    kalman_filter,
)

MATS = np.array([0.25, 0.5, 1, 2, 3, 5, 7, 10, 20, 30])
TRUE = DNSParameters(
    lam=0.6,
    mu=np.array([5.0, -1.5, -0.5]),
    A=np.array([[0.98, 0.02, 0.0], [0.0, 0.95, 0.01], [0.0, 0.0, 0.9]]),
    Q=np.diag([0.25, 0.35, 0.6]) ** 2,
    h=np.full(MATS.size, 0.05),
)


def simulate(p: DNSParameters, T: int, seed: int = 0) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    f = np.zeros((T, 3))
    f[0] = p.mu
    for t in range(1, T):
        f[t] = p.mu + p.A @ (f[t - 1] - p.mu) + rng.multivariate_normal(np.zeros(3), p.Q)
    y = f @ ns_loadings(MATS, p.lam).T + rng.normal(0, 1, (T, MATS.size)) * p.h
    return pd.DataFrame(y, index=pd.date_range("1990-01-31", periods=T, freq="ME"), columns=MATS)


def textbook_filter(y, p):
    """Plain covariance-form Kalman filter, for reference."""
    L = ns_loadings(MATS, p.lam)
    c = p.mu - p.A @ p.mu
    stationary = np.all(np.abs(np.linalg.eigvals(p.A)) < 0.999)
    f, P = p.mu.copy(), (solve_discrete_lyapunov(p.A, p.Q) if stationary else np.eye(3) * 10)
    ll, out = 0.0, []
    for t in range(len(y)):
        if t:
            f, P = c + p.A @ f, p.A @ P @ p.A.T + p.Q
        o = np.isfinite(y[t])
        if o.any():
            Lo = L[o]
            F = Lo @ P @ Lo.T + np.diag(p.h[o] ** 2)
            v = y[t, o] - Lo @ f
            ll += -0.5 * (
                o.sum() * np.log(2 * np.pi) + np.linalg.slogdet(F)[1] + v @ np.linalg.solve(F, v)
            )
            K = P @ Lo.T @ np.linalg.inv(F)
            f, P = f + K @ v, P - K @ Lo @ P
        out.append(f)
    return ll, np.array(out)


@pytest.mark.parametrize("unit_root", [False, True])
def test_filter_matches_textbook_implementation(unit_root):
    p = TRUE
    if unit_root:
        A = p.A.copy()
        A[0] = [1.0, 0.0, 0.0]
        p = DNSParameters(p.lam, p.mu, A, p.Q, p.h)
    y = simulate(TRUE, 120, seed=1).to_numpy().copy()
    y[:30, 0] = np.nan  # a tenor that starts later
    y[50:60, -1] = np.nan  # a tenor that pauses
    y[70, :] = np.nan  # a date with nothing observed
    y[71, 3] = np.nan  # an isolated missing quote
    fast = kalman_filter(y, MATS, p)
    ll, states = textbook_filter(y, p)
    assert fast.loglik == pytest.approx(ll, rel=1e-9)
    np.testing.assert_allclose(fast.filtered, states, atol=1e-8)


def test_transform_round_trip():
    for dyn in ("var", "diag"):
        tr = _Transform(MATS.size, dyn, None, False)
        A = TRUE.A if dyn == "var" else np.diag(np.diag(TRUE.A))
        p = DNSParameters(TRUE.lam, TRUE.mu, A, TRUE.Q, TRUE.h)
        q = tr.unpack(tr.pack(p))
        np.testing.assert_allclose(q.A, p.A)
        np.testing.assert_allclose(q.Q, p.Q, atol=1e-10)
        np.testing.assert_allclose(q.h, p.h)
        assert q.lam == pytest.approx(p.lam)


@pytest.fixture(scope="module")
def fitted():
    return fit_dns(simulate(TRUE, 240, seed=2))


def test_recovers_parameters(fitted):
    p = fitted.params
    assert fitted.converged
    assert p.lam == pytest.approx(TRUE.lam, rel=0.05)
    np.testing.assert_allclose(np.diag(p.A), np.diag(TRUE.A), atol=0.06)
    np.testing.assert_allclose(np.sqrt(np.diag(p.Q)), np.sqrt(np.diag(TRUE.Q)), rtol=0.2)
    np.testing.assert_allclose(p.h, TRUE.h, rtol=0.25)
    assert "BIC" in fitted.summary().index


def test_forecast_distribution(fitted):
    mean1, cov1 = fitted.forecast(1)
    _, cov12 = fitted.forecast(12)
    assert mean1.shape == (MATS.size,) and cov1.shape == (MATS.size, MATS.size)
    assert np.all(np.diag(cov12) > np.diag(cov1))  # uncertainty grows with the horizon
    m, c = fitted.forecast(3, maturities=[4.0, 15.0])
    assert m.shape == (2,) and np.all(np.linalg.eigvalsh(c) > 0)


def test_unit_root_level_is_a_random_walk():
    res = fit_dns(simulate(TRUE, 150, seed=3), dynamics="diag", level_unit_root=True, maxiter=100)
    assert res.params.A[0, 0] == 1.0
    assert np.count_nonzero(res.params.A - np.diag(np.diag(res.params.A))) == 0
    with pytest.raises(ValueError):
        fit_dns(simulate(TRUE, 20), dynamics="bad")


def test_rolling_evaluation():
    y = simulate(TRUE, 300, seed=4)
    ev = evaluate_dns_forecasts(y, horizons=(1, 6), min_train=230, reestimate_every=40)
    assert list(ev.relative_rmse.index) == [1, 6]
    assert ev.n_forecasts[1] == 70 and ev.n_forecasts[6] == 65
    cov = ev.coverage.to_numpy()
    assert np.all((cov >= 0) & (cov <= 1))
    # Data generated by the model itself and a long enough training sample: the
    # 80% intervals hold. (With ~70 months of training, estimation error that the
    # intervals ignore makes them far too narrow.)
    assert 0.7 < np.nanmean(cov) < 0.9


def test_measurement_noise_has_a_floor(fitted):
    from nss_engine.statespace import _H_FLOOR

    tr = _Transform(MATS.size, "var", None, False)
    theta = tr.pack(fitted.params)
    theta[-MATS.size :] = -50.0  # push every noise sd towards zero
    assert np.all(tr.unpack(theta).h >= _H_FLOOR)
